name: wearable_streaming
description: A simple Heart Rate streaming app.
publish_to: 'none' 
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^11.0.0
  polar: ^7.0.0
  sembast: ^3.5.0
  path_provider: ^2.1.0
  mdsflutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true