name: mobile_sensing
description: A skeleton app for mobile sensing.
publish_to: 'none' 
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # sensors_plus: ^3.0.3
  # location: ^5.0.3
  # pedometer: ^4.0.0
  # light: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
